"""第一次

Revision ID: 84e8e7526741
Revises: None
Create Date: 2016-07-23 13:19:29.310165

"""

# revision identifiers, used by Alembic.
revision = '84e8e7526741'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=False),
    sa.Column('nickName', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('isAuthenticated', sa.Integer(), nullable=False),
    sa.Column('qq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_index(op.f('ix_users_userID'), 'users', ['userID'], unique=False)
    op.create_index(op.f('ix_users_userName'), 'users', ['userName'], unique=True)
    op.create_table('goods',
    sa.Column('goodID', sa.Integer(), nullable=False),
    sa.Column('goodName', sa.String(length=128), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=False),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('modifyDate', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('freeCount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('compressImage', sa.Text(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('goodID')
    )
    op.create_index(op.f('ix_goods_createDate'), 'goods', ['createDate'], unique=False)
    op.create_index(op.f('ix_goods_goodID'), 'goods', ['goodID'], unique=False)
    op.create_index(op.f('ix_goods_modifyDate'), 'goods', ['modifyDate'], unique=False)
    op.create_table('comments',
    sa.Column('commentID', sa.Integer(), nullable=False),
    sa.Column('goodID', sa.Integer(), nullable=False),
    sa.Column('commentatorID', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commentatorID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['goodID'], ['goods.goodID'], ),
    sa.PrimaryKeyConstraint('commentID')
    )
    op.create_index(op.f('ix_comments_commentID'), 'comments', ['commentID'], unique=False)
    op.create_table('orders',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('goodID', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=False),
    sa.Column('buyerID', sa.Integer(), nullable=False),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('confirmDate', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['goodID'], ['goods.goodID'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_index(op.f('ix_orders_confirmDate'), 'orders', ['confirmDate'], unique=False)
    op.create_index(op.f('ix_orders_createDate'), 'orders', ['createDate'], unique=False)
    op.create_index(op.f('ix_orders_orderID'), 'orders', ['orderID'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_orderID'), table_name='orders')
    op.drop_index(op.f('ix_orders_createDate'), table_name='orders')
    op.drop_index(op.f('ix_orders_confirmDate'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_comments_commentID'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_goods_modifyDate'), table_name='goods')
    op.drop_index(op.f('ix_goods_goodID'), table_name='goods')
    op.drop_index(op.f('ix_goods_createDate'), table_name='goods')
    op.drop_table('goods')
    op.drop_index(op.f('ix_users_userName'), table_name='users')
    op.drop_index(op.f('ix_users_userID'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
