"""更改User表

Revision ID: 9f8b84bef3fd
Revises: 84e8e7526741
Create Date: 2016-07-23 13:22:15.088353

"""

# revision identifiers, used by Alembic.
revision = '9f8b84bef3fd'
down_revision = '84e8e7526741'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'userName',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'userName',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###
