"""增加price, 添加假数据脚本

Revision ID: a64c6dabd865
Revises: 9f8b84bef3fd
Create Date: 2016-07-23 14:32:53.349040

"""

# revision identifiers, used by Alembic.
revision = 'a64c6dabd865'
down_revision = '9f8b84bef3fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('price', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'price')
    ### end Alembic commands ###
