"""更新商品联系方式

Revision ID: bbe65f03489b
Revises: a64c6dabd865
Create Date: 2016-07-24 13:06:58.145613

"""

# revision identifiers, used by Alembic.
revision = 'bbe65f03489b'
down_revision = 'a64c6dabd865'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('contact_qq', sa.Integer(), nullable=False))
    op.add_column('goods', sa.Column('contact_tel', sa.Integer(), nullable=False))
    op.add_column('goods', sa.Column('contact_wechat', sa.String(length=64), nullable=False))
    op.drop_column('goods', 'contact')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('contact', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('goods', 'contact_wechat')
    op.drop_column('goods', 'contact_tel')
    op.drop_column('goods', 'contact_qq')
    ### end Alembic commands ###
