"""添加地址、次数、广告语

Revision ID: cf116f4697d1
Revises: bbe65f03489b
Create Date: 2016-07-24 15:49:06.062274

"""

# revision identifiers, used by Alembic.
revision = 'cf116f4697d1'
down_revision = 'bbe65f03489b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('goodsID', sa.Integer(), nullable=True))
    op.alter_column('comments', 'commentatorID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'goods', ['goodsID'], ['goodID'])
    op.drop_column('comments', 'goodID')
    op.add_column('goods', sa.Column('address', sa.String(length=128), nullable=False))
    op.add_column('goods', sa.Column('poster', sa.String(length=128), nullable=False))
    op.add_column('goods', sa.Column('times', sa.Integer(), nullable=True))
    op.alter_column('orders', 'createDate',
               existing_type=mysql.DATETIME(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'createDate',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('goods', 'times')
    op.drop_column('goods', 'poster')
    op.drop_column('goods', 'address')
    op.add_column('comments', sa.Column('goodID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_2', 'comments', 'goods', ['goodID'], ['goodID'])
    op.alter_column('comments', 'commentatorID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('comments', 'goodsID')
    ### end Alembic commands ###
