"""添加用户头像

Revision ID: e7868a71f561
Revises: cf116f4697d1
Create Date: 2016-07-26 20:33:21.009341

"""

# revision identifiers, used by Alembic.
revision = 'e7868a71f561'
down_revision = 'cf116f4697d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commitTime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('compressPicture', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('picture', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('users', 'compressPicture')
    op.drop_column('comments', 'commitTime')
    ### end Alembic commands ###
